# Generated by Django 4.1.3 on 2022-12-04 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashiriblogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='location',
        ),
    ]
